- name: Install chrony
  ansible.builtin.apt:
    name: chrony
    state: present

- name: chrony ???
  ansible.builtin.lineinfile:
    dest: /etc/systemd/system/chronyd.service
    regexp: "^ConditionCapability="
    line: '#ConditionCapability=CAP_SYS_TIME'
  notify: restart_chrony

- name: chrony ???
  ansible.builtin.lineinfile:
    dest: /etc/default/chrony
    regexp: "^DAEMON_OPTS="
    line: 'DAEMON_OPTS="-F -1 -x"'
  notify: restart_chrony

- name: chrony ???
  ansible.builtin.copy:
    src: "chrony.conf"
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart_chrony

