# REDIRECT DNS FROM Vpn TO Dmz

- name: DNAT PREROUTING DNS IPv4
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    chain_management: true
    state: present
    action: append
    protocol: udp
    destination_port: 53
    source: 172.32.20.0/24
    destination: 0.0.0.0/0
    to_destination: 192.168.40.10
    ctstate: NEW
    jump: DNAT
    comment: 'DNS'
    ip_version: ipv4
  notify: save_rules

# ACCEPT FORWARD DNS FROM Vpn TO Dmz

- name: ACCEPT FORWARD DNS IPv4
  ansible.builtin.iptables:
    table: filter
    chain: FORWARD
    chain_management: true
    state: present
    action: append
    protocol: udp
    destination_port: 53
    source: 172.32.20.0/24
    destination: 192.168.40.10/32
    ctstate: NEW
    jump: ACCEPT
    comment: 'DNS'
    ip_version: ipv4
  notify: save_rules

# ACCEPT FORWARD SSH FROM Vpn TO Dmz

- name: ACCEPT FORWARD SSH IPv4
  ansible.builtin.iptables:
    table: filter
    chain: FORWARD
    chain_management: true
    state: present
    action: append
    protocol: tcp
    destination_port: 22
    source: 172.32.20.0/24
    destination: 192.168.40.22/32
    ctstate: NEW
    jump: ACCEPT
    comment: 'SSH'
    ip_version: ipv4
  notify: save_rules

# ACCEPT FORWARD SSH FROM Dmz TO Router

- name: ACCEPT FORWARD LIMIT SSH IPv4
  ansible.builtin.iptables:
    table: filter
    chain: FORWARD
    chain_management: true
    state: present
    action: append
    protocol: tcp
    destination_port: 22
    source: 192.168.40.22/32
    destination: 172.32.16.1/32
    ctstate: NEW
    syn: match
    limit: 2/second
    limit_burst: 20
    jump: ACCEPT
    comment: 'SSH'
    ip_version: ipv4
  notify: save_rules

- name: ACCEPT FORWARD LIMIT SSH IPv4
  ansible.builtin.iptables:
    table: filter
    chain: FORWARD
    chain_management: true
    state: present
    action: append
    protocol: tcp
    destination_port: 22
    source: 192.168.40.29/32
    destination: 172.32.16.1/32
    ctstate: NEW
    syn: match
    limit: 2/second
    limit_burst: 20
    jump: ACCEPT
    comment: 'SSH'
    ip_version: ipv4
  notify: save_rules

# ACCEPT FORWARD REPO FROM Router TO Dmz

- name: ACCEPT FORWARD HTTP (REPO) IPv4
  ansible.builtin.iptables:
    table: filter
    chain: FORWARD
    chain_management: true
    state: present
    action: append
    protocol: tcp
    destination_port: 80
    source: 172.32.16.1/32
    destination: 192.168.40.24/32
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: 'REPO'
    ip_version: ipv4
  notify: save_rules

# ACCEPT FORWARD HTTP FROM Vpn TO REPO

- name: ACCEPT FORWARD HTTP IPv4
  ansible.builtin.iptables:
    table: filter
    chain: FORWARD
    chain_management: true
    state: present
    action: append
    protocol: tcp
    destination_port: 80
    source: 0.0.0.0/0
    destination: 192.168.40.24/32
    ctstate: NEW
    jump: ACCEPT
    comment: 'HTTP'
    ip_version: ipv4
  notify: save_rules

# ACCEPT FORWARD HTTP FROM Vpn TO FTP

- name: ACCEPT FORWARD HTTP IPv4
  ansible.builtin.iptables:
    table: filter
    chain: FORWARD
    chain_management: true
    state: present
    action: append
    protocol: tcp
    destination_port: 80
    source: 0.0.0.0/0
    destination: 192.168.40.20/32
    ctstate: NEW
    jump: ACCEPT
    comment: 'HTTP'
    ip_version: ipv4
  notify: save_rules

# ACCEPT FORWARD HTTP FROM Vpn TO HA

- name: ACCEPT FORWARD HTTP IPv4
  ansible.builtin.iptables:
    table: filter
    chain: FORWARD
    chain_management: true
    state: present
    action: append
    protocol: tcp
    destination_port: 80
    source: 0.0.0.0/0
    destination: 192.168.40.16/32
    ctstate: NEW
    jump: ACCEPT
    comment: 'HTTP'
    ip_version: ipv4
  notify: save_rules

# ACCEPT FORWARD HTTP FROM Vpn TO WEB

- name: ACCEPT FORWARD HTTP IPv4
  ansible.builtin.iptables:
    table: filter
    chain: FORWARD
    chain_management: true
    state: present
    action: append
    protocol: tcp
    destination_port: 80
    source: 0.0.0.0/0
    destination: 192.168.40.14/32
    ctstate: NEW
    jump: ACCEPT
    comment: 'HTTP'
    ip_version: ipv4
  notify: save_rules

# ACCEPT FORWARD HTTP(S) FROM Apn TO Internet

- name: ACCEPT FORWARD HTTP(S) IPv4
  ansible.builtin.iptables:
    table: filter
    chain: FORWARD
    chain_management: true
    state: present
    action: append
    protocol: tcp
    destination_ports: '80,443'
    source: 172.32.20.0/24
    destination: 0.0.0.0/0
    ctstate: NEW
    jump: ACCEPT
    comment: 'HTTP(S)'
    ip_version: ipv4
  notify: save_rules

# ACCEPT FORWARD Mensajeria FROM Apn TO Internet

- name: ACCEPT FORWARD Mensajeria IPv4
  ansible.builtin.iptables:
    table: filter
    chain: FORWARD
    chain_management: true
    state: present
    action: append
    protocol: tcp
    destination_ports: '1756,3478,5222,5223,5224,5228'
    source: 172.32.20.0/24
    destination: 0.0.0.0/0
    ctstate: NEW
    jump: ACCEPT
    comment: 'Mensajeria'
    ip_version: ipv4
  notify: save_rules

# ACCEPT FORWARD Mensajeria FROM Apn TO Internet

- name: ACCEPT FORWARD Mensajeria IPv4
  ansible.builtin.iptables:
    table: filter
    chain: FORWARD
    chain_management: true
    state: present
    action: append
    protocol: udp
    destination_ports: '3478,5222,46979'
    source: 172.32.20.0/24
    destination: 0.0.0.0/0
    ctstate: NEW
    jump: ACCEPT
    comment: 'Mensajeria'
    ip_version: ipv4
  notify: save_rules

# ACCEPT FORWARD Jitsi Meet FROM Apn TO Internet

- name: ACCEPT FORWARD Jitsi Meet IPv4
  ansible.builtin.iptables:
    table: filter
    chain: FORWARD
    chain_management: true
    state: present
    action: append
    protocol: udp
    destination_ports: '10000:20000'
    source: 172.32.20.0/24
    destination: 0.0.0.0/0
    ctstate: NEW
    jump: ACCEPT
    comment: 'Jitsi Meet'
    ip_version: ipv4
  notify: save_rules

# REDIRECT HA FROM Vpn TO Dmz

- name: DNAT PREROUTING HA IPv4
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    chain_management: true
    state: present
    action: append
    protocol: tcp
    destination_ports: '80,443'
    source: 172.32.20.0/24
    destination: 172.32.16.20/32
    to_destination: 192.168.40.16
    ctstate: NEW
    jump: DNAT
    comment: 'HA'
    ip_version: ipv4
  notify: save_rules

# ACCEPT FORWARD HA FROM Vpn TO Dmz

- name: ACCEPT FORWARD HA IPv4
  ansible.builtin.iptables:
    table: filter
    chain: FORWARD
    chain_management: true
    state: present
    action: append
    protocol: tcp
    destination_ports: '80,443'
    source: 172.32.20.0/24
    destination: 192.168.40.16/32
    ctstate: NEW
    jump: ACCEPT
    comment: 'HA'
    ip_version: ipv4
  notify: save_rules

# REDIRECT NTP FROM Vpn TO Dmz

- name: DNAT PREROUTING NTP IPv4
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    chain_management: true
    state: present
    action: append
    protocol: udp
    destination_port: 123
    source: 172.32.20.0/24
    destination: 0.0.0.0/0
    to_destination: 192.168.40.26
    ctstate: NEW
    jump: DNAT
    comment: 'NTP'
    ip_version: ipv4
  notify: save_rules

# ACCEPT FORWARD NTP FROM Vpn TO Dmz

- name: ACCEPT FORWARD NTP IPv4
  ansible.builtin.iptables:
    table: filter
    chain: FORWARD
    chain_management: true
    state: present
    action: append
    protocol: udp
    destination_port: 123
    source: 172.32.20.0/24
    destination: 192.168.40.26/32
    ctstate: NEW
    jump: ACCEPT
    comment: 'NTP'
    ip_version: ipv4
  notify: save_rules

