- name: Configurar email HIPS 1
  ansible.builtin.lineinfile:
    dest: /etc/fail2ban/jail.local
    regexp: "^destemail ="
    line: "destemail = {{ EMAIL_NOTIFICATION }}"
  notify: restart_fail2ban

- name: Configurar email HIPS 2
  ansible.builtin.lineinfile:
    dest: /etc/fail2ban/jail.local
    regexp: "^mta = "
    line: 'mta = mail'
  notify: restart_fail2ban

- name: Configurar email HIPS 3
  ansible.builtin.lineinfile:
    dest: /etc/fail2ban/jail.local
    regexp: "^action = %(action_)s"
    line: 'action = %(action_mwl)s'
  notify: restart_fail2ban
