---
- name: Install MariaDB
  ansible.builtin.apt:
    name:
      - mariadb-server
      - mariadb-client-compat
    state: present

- name: Install Ansible MariaDB support
  ansible.builtin.apt:
    name:
      - python3-mysqldb
    state: present
